package com.emranhss.HRM_system.enums;

public enum LeavesType {
  CASUAL_LEAVE,
  SICK_LEAVE,
  EARNED_LEAVE,
  MATERNITY_LEAVE,
  PATERNITY_LEAVE,
  UNPAID_LEAVE,
  COMPENSATORY_LEAVE,
  STUDY_LEAVE
}
